<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishTrimmed>true</PublishTrimmed>
     
   
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>

  </PropertyGroup>




  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.29" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.11" PrivateAssets="all" />
    <PackageReference Include="Blazored.Modal" Version="7.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Localization" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="8.0.29" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.6" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.11.0" />
  </ItemGroup>


<Target Name="CopyCustomWebConfig" AfterTargets="Publish">
  <Copy SourceFiles="web.config" DestinationFolder="$(PublishDir)" />
</Target>

</Project>
